export const UPDATE_FORM_VALUES = "UPDATE_FORM_VALUES";
export const INCREMENT_CURRENT_SCREEN = "INCREMENT_CURRENT_SCREEN";
export const DECREMENT_CURRENT_SCREEN = "DECREMENT_CURRENT_SCREEN";
export const NAVIGATE_TO_SCREEN = "NAVIGATE_TO_SCREEN";
